import { useState, useEffect } from 'react';
import { CreditCard, Download, CheckCircle, Clock, DollarSign } from 'lucide-react';
import { useAuth } from '../../lib/auth';
import { supabase, type FeeChallan, type FeeChallanItem } from '../../lib/supabase';
import { PortalCard, PortalPageHeader, PortalButton, PortalLoading, Badge, EmptyState, StatTile } from '../../components/portal-ui';

export default function FeeChallanPage() {
  const { user } = useAuth();
  const [challans, setChallans] = useState<FeeChallan[]>([]);
  const [items, setItems] = useState<Record<string, FeeChallanItem[]>>({});
  const [loading, setLoading] = useState(true);
  const [paying, setPaying] = useState<string | null>(null);

  useEffect(() => {
    (async () => {
      if (!user?.id) { setLoading(false); return; }
      const { data: challanData } = await supabase
        .from('fee_challans')
        .select('*')
        .eq('student_id', user.id)
        .order('created_at', { ascending: false });
      const challanList = (challanData as FeeChallan[]) ?? [];
      setChallans(challanList);

      // Fetch items for each challan
      const itemsMap: Record<string, FeeChallanItem[]> = {};
      for (const c of challanList) {
        const { data: itemList } = await supabase
          .from('fee_challan_items')
          .select('*')
          .eq('challan_id', c.id)
          .order('sort_order', { ascending: true });
        itemsMap[c.id] = (itemList as FeeChallanItem[]) ?? [];
      }
      setItems(itemsMap);
      setLoading(false);
    })();
  }, [user?.id]);

  const totalDue = challans
    .filter((c) => c.status !== 'paid')
    .reduce((sum, c) => sum + (c.total_amount + (c.fine_amount || 0) - (c.paid_amount || 0)), 0);
  const totalPaid = challans.reduce((sum, c) => sum + (c.paid_amount || 0), 0);
  const pendingCount = challans.filter((c) => c.status !== 'paid').length;

  const handlePay = async (challan: FeeChallan) => {
    setPaying(challan.id);
    const grandTotal = challan.total_amount + (challan.fine_amount || 0);
    await supabase.from('fee_challans').update({
      status: 'paid',
      paid_amount: grandTotal,
      payment_date: new Date().toISOString().split('T')[0],
    }).eq('id', challan.id);
    setPaying(null);
    window.location.reload();
  };

  const downloadChallan = async (challanId: string) => {
    const url = `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/generate-fee-challan?challan_id=${challanId}`;
    try {
      const response = await fetch(url);
      if (!response.ok) throw new Error('Failed to generate PDF');
      const blob = await response.blob();
      const downloadUrl = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = downloadUrl;
      a.download = `challan-${challanId}.pdf`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(downloadUrl);
    } catch (err) {
      console.error('Challan download failed:', err);
      window.open(url, '_blank');
    }
  };

  if (loading) return <PortalLoading />;

  return (
    <div className="animate-fade-in">
      <PortalPageHeader
        title="Fee Challan"
        subtitle="View and pay your tuition and other fees"
        icon={CreditCard}
      />

      {/* Summary */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6">
        <StatTile label="Total Due" value={`$${totalDue.toLocaleString()}`} icon={DollarSign} color="red" />
        <StatTile label="Total Paid" value={`$${totalPaid.toLocaleString()}`} icon={CheckCircle} color="green" />
        <StatTile label="Pending Challans" value={pendingCount} icon={Clock} color="gold" />
      </div>

      {/* Fee challans */}
      {challans.length === 0 ? (
        <EmptyState icon={CreditCard} title="No fee challans" message="Your fee challans will appear here once generated by the accounts office." />
      ) : (
        <div className="space-y-4">
          {challans.map((challan) => {
            const grandTotal = challan.total_amount + (challan.fine_amount || 0);
            const balance = grandTotal - (challan.paid_amount || 0);
            const challanItems = items[challan.id] || [];
            return (
              <PortalCard key={challan.id} className="overflow-hidden">
                {/* Header */}
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 p-6 border-b border-ink-100">
                  <div className="flex items-start gap-4">
                    <div className={`w-12 h-12 rounded-xl flex items-center justify-center ${challan.status === 'paid' ? 'bg-green-100' : 'bg-amber-100'}`}>
                      <CreditCard className={challan.status === 'paid' ? 'text-green-600' : 'text-amber-600'} size={24} />
                    </div>
                    <div>
                      <div className="flex items-center gap-3">
                        <h3 className="text-lg font-bold text-ink-900">{challan.challan_number}</h3>
                        <Badge variant={challan.status === 'paid' ? 'success' : challan.status === 'overdue' ? 'error' : challan.status === 'partial' ? 'warning' : 'info'}>
                          {challan.status}
                        </Badge>
                      </div>
                      <div className="text-sm text-ink-500 mt-1">
                        Session: {challan.session}
                        {challan.semester && ` · Semester ${challan.semester}`}
                        {challan.due_date && ` · Due: ${new Date(challan.due_date).toLocaleDateString()}`}
                        {challan.payment_date && ` · Paid: ${new Date(challan.payment_date).toLocaleDateString()}`}
                      </div>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <PortalButton variant="secondary" onClick={() => downloadChallan(challan.id)}>
                      <Download size={16} /> View / Print
                    </PortalButton>
                    {challan.status !== 'paid' && (
                      <PortalButton variant="gold" onClick={() => handlePay(challan)} disabled={paying === challan.id}>
                        {paying === challan.id ? 'Processing...' : 'Pay Now'}
                      </PortalButton>
                    )}
                  </div>
                </div>

                {/* Line items */}
                {challanItems.length > 0 && (
                  <div className="px-6 py-4">
                    <table className="w-full text-sm">
                      <thead className="text-ink-500">
                        <tr>
                          <th className="text-left pb-2 font-medium">Fee Head</th>
                          <th className="text-right pb-2 font-medium">Amount</th>
                        </tr>
                      </thead>
                      <tbody>
                        {challanItems.map((item) => (
                          <tr key={item.id} className="border-t border-ink-50">
                            <td className="py-2.5 text-ink-700">{item.fee_head_name}</td>
                            <td className="py-2.5 text-right text-ink-900 font-medium">${item.amount.toLocaleString()}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                )}

                {/* Totals */}
                <div className="px-6 py-4 bg-ink-50 border-t border-ink-100">
                  <div className="ml-auto w-full max-w-xs space-y-1.5">
                    <div className="flex justify-between text-sm">
                      <span className="text-ink-500">Subtotal</span>
                      <span className="text-ink-900 font-medium">${challan.total_amount.toLocaleString()}</span>
                    </div>
                    {(challan.fine_amount > 0) && (
                      <div className="flex justify-between text-sm">
                        <span className="text-ink-500">Fine</span>
                        <span className="text-rose-600 font-medium">${challan.fine_amount.toLocaleString()}</span>
                      </div>
                    )}
                    {(challan.paid_amount > 0) && (
                      <div className="flex justify-between text-sm">
                        <span className="text-ink-500">Paid</span>
                        <span className="text-green-600 font-medium">${challan.paid_amount.toLocaleString()}</span>
                      </div>
                    )}
                    <div className="flex justify-between pt-2 border-t border-ink-200">
                      <span className="font-bold text-ink-900">Grand Total</span>
                      <span className="font-bold text-ink-900">${grandTotal.toLocaleString()}</span>
                    </div>
                    {balance > 0 && challan.status !== 'paid' && (
                      <div className="flex justify-between">
                        <span className="font-semibold text-rose-600">Balance Due</span>
                        <span className="font-bold text-rose-600">${balance.toLocaleString()}</span>
                      </div>
                    )}
                  </div>
                </div>
              </PortalCard>
            );
          })}
        </div>
      )}
    </div>
  );
}
